'use client';

import Image from 'next/image';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowRight, BarChart3, BriefcaseBusiness, Check, Cloud, Code2, Database, Download, ExternalLink, Facebook, Github, Globe2, Headphones, Linkedin, Mail, Menu, MessageCircle, Moon, Search, Server, Smartphone, Sun, Users, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

const nav=['About','Services','Projects','Process','Pricing','Blog','Contact'];
const fade={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.65}};

const services=[
 ['Web Development','Modern, fast, responsive websites and web applications.',Globe2],
 ['Business Systems','Custom platforms shaped around your actual workflow.',Code2],
 ['POS Solutions','Restaurant, café, retail and multi-branch operations.',Database],
 ['SaaS Development','Secure multi-tenant cloud products and dashboards.',Cloud],
 ['Mobile-Friendly Apps','Responsive experiences for desktop, tablet and mobile.',Smartphone],
 ['Deployment & Support','Domain, hosting, SSL, cloud setup, training and maintenance.',Server]
];
const projects=[
 {title:'ABOTRIX Commercial SaaS',type:'Multi-industry cloud platform',desc:'Restaurant, hotel, travel, clinic, retail and other business modules in one secure cloud platform.',tags:['SaaS','Cloud','Multi-tenant'],gradient:'from-emerald-300 via-emerald-500 to-slate-950'},
 {title:'TSIKBO POS Enterprise',type:'Restaurant POS and operations',desc:'Ordering, KDS, inventory, payroll, reporting, loyalty and multi-branch management.',tags:['POS','KDS','Inventory'],gradient:'from-orange-300 via-orange-500 to-slate-950'},
 {title:'Crew Management System',type:'Automated workforce monitoring',desc:'Crew records, disembarkation alerts, birthday reminders and operational reports.',tags:['Alerts','Reports','Offline'],gradient:'from-sky-300 via-blue-500 to-slate-950'},
 {title:'Hotel & Travel Platform',type:'Booking and operations platform',desc:'Reservations, packages, customer records, billing and management dashboards.',tags:['Travel','Hotel','Booking'],gradient:'from-cyan-300 via-teal-500 to-slate-950'}
];
const posts=[
 ['How a Business Website Helps You Win More Clients','A practical guide to credibility, inquiries and online visibility.','Business Website'],
 ['What a Modern POS System Should Include','Key modules for restaurant, retail and multi-branch operations.','POS Systems'],
 ['When Your Business Needs Custom Software','Signs that spreadsheets and manual workflows are already costing you time.','Business Automation']
];

export default function Home(){
 const [dark,setDark]=useState(true); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(true); const [filter,setFilter]=useState('All');
 useEffect(()=>{const t=setTimeout(()=>setLoading(false),900);return()=>clearTimeout(t)},[]);
 useEffect(()=>document.documentElement.classList.toggle('light',!dark),[dark]);
 const year=useMemo(()=>new Date().getFullYear(),[]);
 const tags=['All','SaaS','POS','Alerts','Travel'];
 const visible=filter==='All'?projects:projects.filter(p=>p.tags.includes(filter));
 return <>
 <AnimatePresence>{loading&&<motion.div exit={{opacity:0}} className="fixed inset-0 z-[100] grid place-items-center bg-ink"><motion.div initial={{scale:.8,opacity:0}} animate={{scale:1,opacity:1}} className="text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-accent text-3xl font-black text-ink shadow-glow">A</div><p className="mt-5 font-bold tracking-[.25em]">ABOTRIX</p><p className="mt-1 text-xs text-white/40">Loading portfolio...</p></motion.div></motion.div>}</AnimatePresence>
 <main className="min-h-screen overflow-hidden bg-ink text-white light:bg-[#f5faf7] light:text-[#0c1711]">
 <div className="fixed inset-0 -z-10 bg-grid bg-[size:36px_36px] opacity-60"/><div className="fixed left-1/2 top-20 -z-10 h-[520px] w-[520px] -translate-x-1/2 rounded-full bg-accent/10 blur-[120px]"/>
 <header className="fixed inset-x-0 top-0 z-50 border-b border-emerald-300/10 bg-ink/80 backdrop-blur-xl light:bg-white/85"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><a href="#home" className="flex items-center gap-3 font-extrabold tracking-wide"><span className="grid h-10 w-10 place-items-center rounded-xl bg-accent text-ink">A</span><span>ABOTRIX<small className="block text-[10px] font-medium text-white/45 light:text-black/45">Rodrigo Maglapid</small></span></a><nav className="hidden items-center gap-6 text-sm text-white/70 light:text-black/65 xl:flex">{nav.map(x=><a key={x} href={`#${x.toLowerCase()}`} className="transition hover:text-accent">{x}</a>)}</nav><div className="flex items-center gap-2"><button onClick={()=>setDark(!dark)} className="rounded-full border border-white/10 p-2.5 light:border-black/10">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><a href="#contact" className="hidden rounded-full bg-accent px-5 py-2.5 text-sm font-bold text-ink sm:block">Let&apos;s Talk</a><button className="xl:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<div className="glass mx-4 mb-4 rounded-2xl p-4 xl:hidden">{nav.map(x=><a onClick={()=>setOpen(false)} key={x} href={`#${x.toLowerCase()}`} className="block rounded-xl px-4 py-3 hover:bg-accent/10">{x}</a>)}</div>}</header>

 <section id="home" className="mx-auto grid min-h-screen max-w-7xl items-center gap-12 px-5 pb-16 pt-32 lg:grid-cols-[1.05fr_.95fr]"><motion.div {...fade}><span className="inline-flex items-center gap-2 rounded-full border border-accent/25 bg-accent/10 px-4 py-2 text-xs font-bold text-accent"><span className="h-2 w-2 rounded-full bg-accent"/> SOFTWARE DEVELOPER</span><h1 className="mt-7 max-w-3xl text-balance text-5xl font-extrabold leading-[1.02] tracking-[-.05em] sm:text-6xl xl:text-7xl">I build solutions that <span className="text-accent">drive results.</span></h1><p className="mt-6 max-w-2xl text-lg text-white/60 light:text-black/60">I&apos;m Rodrigo C. Maglapid Jr., a software developer specializing in business automation, modern websites, POS systems, SaaS platforms and cloud-ready applications.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#contact" className="inline-flex items-center gap-2 rounded-xl bg-accent px-6 py-4 font-bold text-ink">Hire Me <ArrowRight size={18}/></a><a href="#projects" className="rounded-xl border border-white/15 px-6 py-4 font-bold light:border-black/15">View My Work</a><a href="#about" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-6 py-4 font-bold light:border-black/15"><Download size={18}/> Download CV</a></div><div className="mt-10 grid max-w-2xl grid-cols-3 gap-3"><Stat n="5+" label="Systems"/><Stat n="20+" label="Modules"/><Stat n="100%" label="Responsive"/></div><div className="mt-7 flex items-center gap-3 text-white/45 light:text-black/45"><span className="text-xs">Let&apos;s connect:</span><Social icon={<Github size={16}/>} label="GitHub"/><Social icon={<Linkedin size={16}/>} label="LinkedIn"/><Social icon={<Facebook size={16}/>} label="Facebook"/><Social icon={<MessageCircle size={16}/>} label="WhatsApp"/></div></motion.div><motion.div {...fade} className="relative mx-auto w-full max-w-xl"><div className="absolute inset-12 rounded-full bg-accent/20 blur-3xl"/><div className="relative overflow-hidden rounded-[2.5rem] border border-accent/25 bg-gradient-to-b from-accent/10 to-panel shadow-glow"><Image src="/rodrigo-profile.png" alt="Rodrigo Maglapid in formal business attire" width={1200} height={1600} priority className="h-[610px] w-full object-cover object-top"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-ink via-ink/70 to-transparent p-7 pt-28"><p className="text-sm text-accent">Cavite, Philippines</p><h2 className="text-2xl font-bold">Rodrigo C. Maglapid Jr.</h2><p className="text-white/55">Software Developer · ABOTRIX</p></div></div></motion.div></section>

 <section className="mx-auto max-w-7xl px-5 pb-8"><div className="glass grid gap-5 rounded-3xl p-6 sm:grid-cols-2 lg:grid-cols-5"><Metric icon={<BriefcaseBusiness/>} value="5+" label="Business Systems"/><Metric icon={<Code2/>} value="20+" label="Modules Developed"/><Metric icon={<Users/>} value="Multi" label="Industries Served"/><Metric icon={<BarChart3/>} value="Cloud" label="Reports & Analytics"/><Metric icon={<Headphones/>} value="Support" label="Training & Maintenance"/></div></section>

 <section id="about" className="mx-auto max-w-7xl px-5 py-24"><motion.div {...fade} className="glass grid gap-10 rounded-[2rem] p-7 md:p-10 lg:grid-cols-[.7fr_1.3fr]"><div className="relative min-h-96 overflow-hidden rounded-3xl"><Image src="/rodrigo-profile.png" alt="Rodrigo Maglapid professional portrait" fill className="object-cover object-top"/></div><div><Label>ABOUT ME</Label><h2 className="section-title mt-4">Building digital solutions that make an impact.</h2><p className="mt-6 text-white/60 light:text-black/60">I combine practical business experience with software development to create systems that are easy to use, scalable and aligned with real operations. My focus includes restaurant POS, business automation, HR and payroll, travel, hotel and multi-industry SaaS platforms.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Business-first approach','Responsive modern design','Cloud-ready architecture','Training and support'].map(x=><div key={x} className="flex items-center gap-3 text-sm"><span className="grid h-7 w-7 place-items-center rounded-full bg-accent/15 text-accent"><Check size={15}/></span>{x}</div>)}</div><div className="mt-8 flex flex-wrap gap-2">{['Next.js','React','TypeScript','Tailwind CSS','Python','FastAPI','PostgreSQL','Docker','Google Cloud','Cloudflare'].map(x=><span key={x} className="rounded-full border border-accent/20 bg-accent/5 px-3 py-2 text-xs text-accent">{x}</span>)}</div></div></motion.div></section>

 <Section id="services" label="SERVICES" title="Professional services for modern businesses." intro="From your first website to a complete enterprise platform."><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([title,desc,Icon]:any)=><article key={title} className="glass rounded-3xl p-7 transition hover:-translate-y-1 hover:border-accent/50"><Icon className="text-accent"/><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 text-sm text-white/55 light:text-black/55">{desc}</p></article>)}</div></Section>

 <Section id="projects" label="FEATURED PROJECTS" title="Projects I&apos;m proud of." intro="Filter the work by solution type and request a private demonstration."><div className="mt-8 flex flex-wrap gap-2">{tags.map(t=><button key={t} onClick={()=>setFilter(t)} className={`rounded-full px-4 py-2 text-sm ${filter===t?'bg-accent text-ink':'glass'}`}>{t}</button>)}</div><div className="mt-8 grid gap-5 md:grid-cols-2">{visible.map(p=><article key={p.title} className="glass overflow-hidden rounded-3xl transition hover:-translate-y-1"><div className={`relative h-64 bg-gradient-to-br ${p.gradient} p-6`}><span className="rounded-full bg-black/35 px-3 py-1 text-xs">2026</span><div className="absolute inset-x-8 bottom-0 h-44 rounded-t-2xl border border-white/20 bg-black/45 p-4 shadow-2xl"><div className="h-4 w-28 rounded bg-white/20"/><div className="mt-5 grid grid-cols-3 gap-3"><i className="h-16 rounded bg-white/10"/><i className="h-16 rounded bg-white/10"/><i className="h-16 rounded bg-white/10"/></div><div className="mt-3 h-8 rounded bg-accent/30"/></div></div><div className="p-6"><p className="text-xs font-bold text-accent">{p.type}</p><h3 className="mt-2 text-2xl font-bold">{p.title}</h3><p className="mt-3 text-sm text-white/55 light:text-black/55">{p.desc}</p><div className="mt-5 flex flex-wrap gap-2">{p.tags.map(t=><span key={t} className="rounded-full bg-accent/10 px-3 py-1 text-xs text-accent">{t}</span>)}</div><a href="#contact" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-accent">Request demo <ExternalLink size={15}/></a></div></article>)}</div></Section>

 <Section id="process" label="MY PROCESS" title="A clear path from idea to launch." intro="Each project is divided into practical milestones."><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['01','Discovery','We discuss your business, users, features, budget and timeline.'],['02','Plan & Design','I prepare scope, system structure and interface direction.'],['03','Build & Test','Development, testing and review happen in measurable milestones.'],['04','Launch & Support','Deployment, training and agreed post-launch support.']].map(([n,t,d])=><article key={n} className="glass rounded-3xl p-7"><p className="text-sm font-black text-accent">{n}</p><h3 className="mt-12 text-xl font-bold">{t}</h3><p className="mt-3 text-sm text-white/55 light:text-black/55">{d}</p></article>)}</div></Section>

 <Section id="pricing" label="PRICING" title="Flexible packages for every stage." intro="Final quotations depend on features, integrations and support."><div className="mt-10 grid gap-5 lg:grid-cols-3"><Price name="Business Website" price="₱20,000+" items={['Responsive website','Up to 5 key pages','Basic SEO','Domain and hosting setup','30 days support']}/><Price featured name="Business Platform" price="₱50,000+" items={['Custom dashboard','User roles','Business workflow','Reports and analytics','Deployment and training']}/><Price name="Enterprise System" price="₱120,000+" items={['Advanced modules','Cloud architecture','Multi-branch support','Integrations','3 months support']}/></div></Section>

 <Section id="blog" label="INSIGHTS" title="Practical articles for business owners." intro="Simple explanations about websites, systems and automation."><div className="mt-10 grid gap-5 md:grid-cols-3">{posts.map(([t,d,c])=><article key={t} className="glass rounded-3xl p-7"><span className="text-xs font-bold text-accent">{c}</span><h3 className="mt-5 text-xl font-bold">{t}</h3><p className="mt-3 text-sm text-white/55 light:text-black/55">{d}</p><a href="#contact" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-accent">Discuss this topic <ArrowRight size={15}/></a></article>)}</div></Section>

 <section id="contact" className="mx-auto max-w-7xl px-5 py-24"><motion.div {...fade} className="overflow-hidden rounded-[2.5rem] border border-accent/25 bg-gradient-to-br from-accent/15 via-panel to-ink p-7 md:p-12"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><Label>CONTACT</Label><h2 className="section-title mt-4">Let&apos;s build something amazing together.</h2><p className="mt-5 text-white/55">Tell me about your business, required features and target timeline. Your inquiry will be sent to support@abotrix.com.</p><a href="mailto:support@abotrix.com" className="mt-8 inline-flex items-center gap-3 text-accent"><Mail/> support@abotrix.com</a></div><form action="https://formsubmit.co/support@abotrix.com" method="POST" className="grid gap-4"><input type="hidden" name="_subject" value="New Portfolio Inquiry"/><input type="hidden" name="_captcha" value="false"/><input type="hidden" name="_template" value="table"/><div className="grid gap-4 sm:grid-cols-2"><input required name="name" placeholder="Your name" className="field"/><input required type="email" name="email" placeholder="Email address" className="field"/></div><div className="grid gap-4 sm:grid-cols-2"><input name="phone" placeholder="Mobile number" className="field"/><select name="project_type" className="field"><option>Business Website</option><option>Custom Business Platform</option><option>POS System</option><option>SaaS Platform</option><option>Other</option></select></div><textarea required name="details" rows={6} placeholder="Tell me about your project..." className="field"/><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-accent px-6 py-4 font-bold text-ink">Send Inquiry <ArrowRight size={18}/></button><p className="text-xs text-white/35">The first submission may require one-time activation from FormSubmit.</p></form></div></motion.div></section>

 <footer className="border-t border-white/10 py-10 light:border-black/10"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 md:flex-row md:items-center md:justify-between"><div><p className="font-extrabold">ABOTRIX · Rodrigo Maglapid</p><p className="text-sm text-white/45 light:text-black/45">Building practical digital solutions for modern businesses.</p></div><div className="flex flex-wrap gap-4 text-sm text-white/55 light:text-black/55">{nav.map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</div><p className="text-sm text-white/40 light:text-black/40">© {year} All rights reserved.</p></div></footer>
 </main></>;
}
function Label({children}:{children:React.ReactNode}){return <span className="inline-flex rounded-full bg-accent/10 px-3 py-1 text-xs font-bold tracking-wider text-accent">{children}</span>}
function Section({id,label,title,intro,children}:{id:string,label:string,title:string,intro:string,children:React.ReactNode}){return <section id={id} className="mx-auto max-w-7xl px-5 py-24"><motion.div {...fade}><Label>{label}</Label><div className="mt-4 flex flex-col justify-between gap-4 md:flex-row md:items-end"><h2 className="section-title max-w-3xl">{title}</h2><p className="max-w-md text-white/55 light:text-black/55">{intro}</p></div>{children}</motion.div></section>}
function Stat({n,label}:{n:string,label:string}){return <div className="glass rounded-2xl p-4"><p className="text-2xl font-black text-accent">{n}</p><p className="text-xs text-white/45 light:text-black/45">{label}</p></div>}
function Metric({icon,value,label}:{icon:React.ReactNode,value:string,label:string}){return <div className="flex items-center gap-3"><span className="text-accent">{icon}</span><div><p className="font-black">{value}</p><p className="text-xs text-white/45 light:text-black/45">{label}</p></div></div>}
function Social({icon,label}:{icon:React.ReactNode,label:string}){return <a href="#contact" aria-label={label} className="grid h-9 w-9 place-items-center rounded-full border border-white/10 transition hover:border-accent hover:text-accent light:border-black/10">{icon}</a>}
function Price({name,price,items,featured=false}:{name:string,price:string,items:string[],featured?:boolean}){return <article className={`rounded-3xl border p-7 ${featured?'border-accent bg-accent/10 shadow-glow':'glass'}`}><p className="text-sm font-bold text-accent">{name}</p><h3 className="mt-4 text-4xl font-black">{price}</h3><p className="mt-2 text-xs text-white/40 light:text-black/40">Final quotation depends on scope.</p><div className="mt-7 grid gap-3">{items.map(x=><p key={x} className="flex items-center gap-3 text-sm"><Check size={16} className="text-accent"/>{x}</p>)}</div><a href="#contact" className={`mt-8 inline-flex w-full items-center justify-center rounded-xl px-5 py-3 font-bold ${featured?'bg-accent text-ink':'border border-white/15 light:border-black/15'}`}>Request a Quote</a></article>}
