'use client';
import Image from 'next/image';
import {AnimatePresence,motion} from 'framer-motion';
import {ArrowRight,BarChart3,BriefcaseBusiness,CalendarDays,Check,Cloud,Code2,Database,Download,ExternalLink,Facebook,Github,Globe2,Headphones,Hotel,Layers3,Linkedin,Mail,Menu,MessageCircle,Moon,Network,PlayCircle,Server,ShieldCheck,Smartphone,Sun,Users,X,Zap} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';

const nav=['About','Services','Projects','Solutions','Process','Pricing','Contact'];
const fade={initial:{opacity:0,y:26},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.68}};
const typing=['Enterprise Software','Restaurant POS Systems','Hotel & Travel Platforms','Business Automation'];
const projects=[
 {title:'ABOTRIX Commercial SaaS',type:'Multi-industry cloud platform',desc:'Tenant dashboards, analytics, billing, user management and industry-specific workspaces.',tags:['SaaS','Cloud','Multi-tenant'],image:'/projects/abotrix-dashboard.jpg'},
 {title:'TSIKBO POS Enterprise',type:'Restaurant POS & operations',desc:'Cashier ordering, KDS, inventory, payroll, reports, loyalty and branch management.',tags:['POS','KDS','Inventory'],image:'/projects/tsikbo-pos.jpg'},
 {title:'Crew Management System',type:'Automated workforce monitoring',desc:'Crew records, document monitoring, disembarkation alerts and operational reporting.',tags:['Crew','Alerts','Reports'],image:'/projects/crew-management.jpg'},
 {title:'Hotel & Travel Platform',type:'Booking and reservation system',desc:'Reservations, room and tour packages, customer records, billing and management dashboards.',tags:['Hotel','Travel','Booking'],image:'/projects/hotel-travel.jpg'}
];
const services=[['Business Websites','Modern websites designed to build trust and generate inquiries.',Globe2],['Custom Business Systems','Dashboards and workflows created around your operations.',Code2],['POS Solutions','Restaurant, café, retail and multi-branch POS systems.',Database],['SaaS Platforms','Secure multi-tenant platforms with billing and roles.',Cloud],['Mobile-Responsive Apps','Interfaces that work across PC, tablet and mobile.',Smartphone],['Cloud Deployment','Domain, SSL, server setup, backups, training and support.',Server]];
const benefits=[['Enterprise Security','Role-based access, tenant isolation and secure deployment.',ShieldCheck],['Multi-Branch Ready','Centralized visibility with branch-level operations.',Network],['Fast & Scalable','Modern architecture that can grow with the business.',Zap],['Industry Modules','Restaurant, hotel, travel, workforce and other solutions.',Layers3],['Cloud Ready','Secure online access, backups and remote management.',Cloud],['Professional Support','Deployment guidance, training and maintenance options.',Headphones]];

export default function Home(){
 const [dark,setDark]=useState(true),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[word,setWord]=useState(0);
 useEffect(()=>{const t=setTimeout(()=>setLoading(false),850);return()=>clearTimeout(t)},[]);
 useEffect(()=>{document.documentElement.classList.toggle('light',!dark)},[dark]);
 useEffect(()=>{const t=setInterval(()=>setWord(v=>(v+1)%typing.length),2400);return()=>clearInterval(t)},[]);
 const year=useMemo(()=>new Date().getFullYear(),[]);
 return <>
 <AnimatePresence>{loading&&<motion.div exit={{opacity:0}} className="fixed inset-0 z-[100] grid place-items-center bg-ink"><motion.div initial={{scale:.75,opacity:0}} animate={{scale:1,opacity:1}} className="text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-accent text-3xl font-black text-ink shadow-glow">A</div><p className="mt-5 font-bold tracking-[.3em]">ABOTRIX</p><p className="mt-1 text-xs text-white/40">Preparing enterprise portfolio...</p></motion.div></motion.div>}</AnimatePresence>
 <main className="min-h-screen overflow-hidden bg-ink text-white light:bg-[#f5faf7] light:text-[#0c1711]">
  <div className="fixed inset-0 -z-10 bg-grid bg-[size:38px_38px] opacity-60"/><div className="fixed left-1/2 top-10 -z-10 h-[620px] w-[620px] -translate-x-1/2 rounded-full bg-accent/10 blur-[140px]"/>
  <header className="fixed inset-x-0 top-0 z-50 border-b border-emerald-300/10 bg-ink/80 backdrop-blur-xl light:bg-white/85"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><a href="#home" className="flex items-center gap-3 font-extrabold tracking-wide"><span className="grid h-10 w-10 place-items-center rounded-xl bg-accent text-ink">A</span><span>ABOTRIX<small className="block text-[10px] font-medium text-white/45 light:text-black/45">Rod Maglapid</small></span></a><nav className="hidden items-center gap-6 text-sm text-white/70 light:text-black/65 xl:flex">{nav.map(x=><a key={x} href={`#${x.toLowerCase()}`} className="transition hover:text-accent">{x}</a>)}</nav><div className="flex items-center gap-2"><button onClick={()=>setDark(!dark)} className="rounded-full border border-white/10 p-2.5 light:border-black/10">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><a href="#contact" className="hidden rounded-full bg-accent px-5 py-2.5 text-sm font-bold text-ink sm:block">Book Consultation</a><button className="xl:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<div className="glass mx-4 mb-4 rounded-2xl p-4 xl:hidden">{nav.map(x=><a onClick={()=>setOpen(false)} key={x} href={`#${x.toLowerCase()}`} className="block rounded-xl px-4 py-3 hover:bg-accent/10">{x}</a>)}</div>}</header>

  <section id="home" className="mx-auto grid min-h-screen max-w-7xl items-center gap-12 px-5 pb-16 pt-32 lg:grid-cols-[1.08fr_.92fr]"><motion.div {...fade}><span className="inline-flex items-center gap-2 rounded-full border border-accent/25 bg-accent/10 px-4 py-2 text-xs font-bold text-accent"><span className="h-2 w-2 rounded-full bg-accent"/> SOFTWARE DEVELOPER & BUSINESS SOLUTIONS</span><h1 className="mt-7 max-w-4xl text-balance text-5xl font-extrabold leading-[1.01] tracking-[-.055em] sm:text-6xl xl:text-7xl">Building software that helps businesses <span className="text-accent">operate smarter.</span></h1><div className="mt-5 h-9 text-xl font-bold text-soft"><AnimatePresence mode="wait"><motion.span key={word} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}}>{typing[word]}</motion.span></AnimatePresence></div><p className="mt-5 max-w-2xl text-lg text-white/60 light:text-black/60">I&apos;m Rod Maglapid, the developer behind ABOTRIX—creating professional websites, POS systems, cloud platforms and practical business applications.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#projects" className="inline-flex items-center gap-2 rounded-xl bg-accent px-6 py-4 font-bold text-ink">Explore Projects <ArrowRight size={18}/></a><a href="#contact" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-6 py-4 font-bold light:border-black/15"><CalendarDays size={18}/> Schedule Consultation</a></div><div className="mt-10 grid max-w-3xl grid-cols-2 gap-3 sm:grid-cols-4"><Stat n="5+" label="Business Systems"/><Stat n="20+" label="Modules"/><Stat n="Multi" label="Industries"/><Stat n="Cloud" label="Ready"/></div><div className="mt-7 flex items-center gap-3 text-white/45 light:text-black/45"><span className="text-xs">Connect:</span><Social icon={<Github size={16}/>} label="GitHub"/><Social icon={<Linkedin size={16}/>} label="LinkedIn"/><Social icon={<Facebook size={16}/>} label="Facebook"/><Social icon={<MessageCircle size={16}/>} label="WhatsApp"/></div></motion.div><motion.div {...fade} className="relative mx-auto w-full max-w-xl">
  <div className="mb-5 grid grid-cols-2 gap-4">
    <div className="rounded-2xl border border-accent/25 bg-accent/5 px-5 py-4">
      <p className="font-black text-accent">Business-first</p>
      <p className="mt-1 text-xs text-white/50 light:text-black/50">Practical solutions</p>
    </div>
    <div className="rounded-2xl border border-accent/25 bg-accent/5 px-5 py-4 text-right">
      <p className="font-black text-accent">Cloud-ready</p>
      <p className="mt-1 text-xs text-white/50 light:text-black/50">Modern deployment</p>
    </div>
  </div>

  <div className="absolute inset-x-12 top-28 bottom-12 -z-10 rounded-full bg-accent/20 blur-[90px]"/>

  <div className="overflow-hidden rounded-[2.5rem] border border-accent/25 bg-panel shadow-glow">
    <Image
      src="/rodrigo-profile.png"
      alt="Rod Maglapid professional portrait"
      width={1200}
      height={1600}
      priority
      className="h-[620px] w-full object-cover object-top"
    />
    <div className="border-t border-accent/20 bg-panel px-7 py-6">
      <p className="text-sm text-accent">Cavite, Philippines</p>
      <h2 className="mt-1 text-3xl font-bold">Rod Maglapid</h2>
      <p className="mt-1 text-white/55 light:text-black/55">Software Developer • ABOTRIX</p>
    </div>
  </div>
</motion.div></section>

  <section className="mx-auto max-w-7xl px-5 pb-12"><div className="glass grid gap-5 rounded-3xl p-6 sm:grid-cols-2 lg:grid-cols-5"><Metric icon={<BriefcaseBusiness/>} value="Custom" label="Business Solutions"/><Metric icon={<Code2/>} value="Modern" label="Web Technologies"/><Metric icon={<Users/>} value="Multi" label="Industry Support"/><Metric icon={<BarChart3/>} value="Reports" label="Analytics Ready"/><Metric icon={<Headphones/>} value="Support" label="Training & Maintenance"/></div></section>

  <section id="about" className="mx-auto max-w-7xl px-5 py-24"><motion.div {...fade} className="glass grid gap-10 rounded-[2rem] p-7 md:p-10 lg:grid-cols-[.7fr_1.3fr]"><div className="relative min-h-[480px] overflow-hidden rounded-3xl"><Image src="/rodrigo-profile.png" alt="Rod Maglapid professional portrait" fill className="object-cover object-top"/></div><div><Label>ABOUT THE DEVELOPER</Label><h2 className="section-title mt-4">Business experience transformed into useful software.</h2><p className="mt-6 text-white/60 light:text-black/60">I focus on building systems that solve real operational problems. Every interface, report and workflow is designed to be understandable for business owners and practical for everyday staff use.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Business-first discovery','Responsive modern UI','Secure cloud deployment','Training and support'].map(x=><div key={x} className="flex items-center gap-3 text-sm"><span className="grid h-7 w-7 place-items-center rounded-full bg-accent/15 text-accent"><Check size={15}/></span>{x}</div>)}</div><div className="mt-8 flex flex-wrap gap-2">{['Next.js','React','TypeScript','Tailwind CSS','Python','FastAPI','PostgreSQL','Docker','Google Cloud','Cloudflare'].map(x=><span key={x} className="rounded-full border border-accent/20 bg-accent/5 px-3 py-2 text-xs text-accent">{x}</span>)}</div></div></motion.div></section>

  <Section id="services" label="SERVICES" title="Professional digital solutions for modern businesses." intro="From a client-facing website to a complete operational platform."><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([t,d,I]:any)=><article key={t} className="glass rounded-3xl p-7 transition duration-300 hover:-translate-y-1 hover:border-accent/50"><I className="text-accent"/><h3 className="mt-8 text-xl font-bold">{t}</h3><p className="mt-3 text-sm text-white/55 light:text-black/55">{d}</p></article>)}</div></Section>

  <Section id="projects" label="FEATURED PROJECTS" title="Realistic previews of systems I&apos;ve developed." intro="Explore some of the enterprise systems and platforms built for different industries and business needs.">
   <div className="mt-10 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
    {projects.map((p,index)=><article key={p.title} className="glass group flex min-w-0 flex-col overflow-hidden rounded-[1.6rem] transition duration-300 hover:-translate-y-1 hover:border-accent/45">
     <div className="relative aspect-[16/10] overflow-hidden border-b border-white/10 bg-black/35 p-2 light:border-black/10 light:bg-black/5">
      <Image src={p.image} alt={`${p.title} dashboard preview`} fill sizes="(min-width:1280px) 25vw, (min-width:640px) 50vw, 100vw" className="object-contain p-2 transition duration-500 group-hover:scale-[1.02]"/>
      <span className={`absolute left-4 top-4 rounded-full px-3 py-1 text-[10px] font-bold text-white ${index===1?'bg-orange-500/90':index===2?'bg-blue-500/90':index===3?'bg-teal-500/90':'bg-emerald-500/90'}`}>{index===0?'SaaS Platform':index===1?'POS System':index===2?'Crew Management':'Travel & Hotel'}</span>
     </div>
     <div className="flex flex-1 flex-col p-5">
      <div className="flex items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg font-black text-ink ${index===1?'bg-orange-500':index===2?'bg-blue-500':index===3?'bg-teal-400':'bg-accent'}`}>{index===0?'A':index===1?'T':index===2?'C':'H'}</span><h3 className="text-lg font-bold leading-tight">{p.title}</h3></div>
      <p className="mt-4 text-sm leading-6 text-white/55 light:text-black/55">{p.desc}</p>
      <div className="mt-5 flex flex-wrap gap-2">{p.tags.map(t=><span key={t} className="rounded-full border border-accent/20 bg-accent/5 px-2.5 py-1 text-[11px] text-accent">{t}</span>)}</div>
      <div className="mt-auto flex flex-wrap gap-x-4 gap-y-2 pt-6"><a href="#contact" className="inline-flex items-center gap-2 text-xs font-bold text-accent">View Demo <ArrowRight size={14}/></a><a href="#contact" className="inline-flex items-center gap-2 text-xs font-bold text-white/65 light:text-black/65">View Features <ExternalLink size={13}/></a></div>
     </div>
    </article>)}
   </div>
   <div className="mt-8 flex justify-center"><a href="#contact" className="inline-flex items-center gap-3 rounded-full border border-accent/60 px-7 py-3 font-bold transition hover:bg-accent hover:text-ink">View All Projects <ArrowRight size={18}/></a></div>
  </Section>

  <Section id="solutions" label="WHY ABOTRIX" title="Designed for growth, control and daily operations." intro="A practical foundation for businesses that need more than a basic website."><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{benefits.map(([t,d,I]:any)=><article key={t} className="glass rounded-3xl p-7"><I className="text-accent"/><h3 className="mt-7 text-xl font-bold">{t}</h3><p className="mt-3 text-sm text-white/55 light:text-black/55">{d}</p></article>)}</div></Section>

  <section className="mx-auto max-w-7xl px-5 py-24">
   <motion.div {...fade} className="relative overflow-hidden rounded-[2.5rem] border border-accent/20 bg-gradient-to-br from-white/[.045] to-accent/[.035] p-7 shadow-glow md:p-10 lg:p-12">
    <div className="pointer-events-none absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-accent/10 to-transparent"/>
    <div className="relative grid items-center gap-12 lg:grid-cols-[.72fr_1.28fr]">
     <div><Label>RESPONSIVE EXPERIENCE</Label><h2 className="section-title mt-4">One system experience across <span className="text-accent">all your devices.</span></h2><p className="mt-5 max-w-lg text-white/55 light:text-black/55">ABOTRIX systems are designed for desktop, laptop, tablet and mobile screens without cutting off important content.</p><div className="mt-7 grid gap-3 text-sm">{['Real-time data synchronization','Consistent user experience','Optimized for all screen sizes','Offline capability for POS'].map(x=><p key={x} className="flex items-center gap-3"><span className="grid h-6 w-6 place-items-center rounded-full border border-accent text-accent"><Check size={14}/></span>{x}</p>)}</div></div>
     <div className="relative mx-auto h-[360px] w-full max-w-[760px] sm:h-[430px] lg:h-[500px]">
      <div className="absolute left-[22%] top-0 z-10 w-[57%] rounded-[1.35rem] border-[8px] border-[#111] bg-[#111] p-1 shadow-2xl sm:border-[10px]"><div className="relative aspect-[16/10] overflow-hidden rounded-lg bg-black"><Image src="/projects/abotrix-dashboard.jpg" alt="ABOTRIX desktop dashboard" fill sizes="600px" className="object-contain"/></div><div className="absolute left-1/2 top-full h-16 w-4 -translate-x-1/2 bg-gradient-to-b from-zinc-400 to-zinc-700"/><div className="absolute left-1/2 top-[calc(100%+3.75rem)] h-3 w-32 -translate-x-1/2 rounded-full bg-zinc-600 sm:w-44"/></div>
      <div className="absolute bottom-3 left-0 z-30 w-[43%] rounded-t-xl border-[7px] border-[#151515] bg-[#151515] p-1 shadow-2xl sm:border-[9px]"><div className="relative aspect-[16/10] overflow-hidden rounded-md bg-black"><Image src="/projects/tsikbo-pos.jpg" alt="TSIKBO POS laptop preview" fill sizes="420px" className="object-contain"/></div><div className="absolute -bottom-3 left-1/2 h-4 w-[115%] -translate-x-1/2 rounded-b-xl bg-gradient-to-b from-zinc-500 to-zinc-800"/></div>
      <div className="absolute bottom-0 right-[8%] z-30 w-[27%] rounded-[1.2rem] border-[7px] border-[#111] bg-[#111] p-1 shadow-2xl sm:border-[9px]"><div className="relative aspect-[3/4] overflow-hidden rounded-lg bg-black"><Image src="/projects/crew-management.jpg" alt="Crew management tablet preview" fill sizes="260px" className="object-cover object-left"/></div></div>
      <div className="absolute bottom-0 right-0 z-40 w-[13%] min-w-[62px] rounded-[1.35rem] border-[6px] border-black bg-black p-1 shadow-2xl"><div className="relative aspect-[9/19] overflow-hidden rounded-[.9rem] bg-black"><Image src="/projects/abotrix-dashboard.jpg" alt="ABOTRIX mobile preview" fill sizes="110px" className="object-cover object-left"/></div></div>
     </div>
    </div>
   </motion.div>
  </section>

  <Section id="process" label="CLIENT JOURNEY" title="A clear process from consultation to support." intro="Every project moves through structured, understandable stages."><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['01','Consultation','Your business, users, pain points, budget and objectives.'],['02','Planning & Design','Scope, modules, architecture and visual direction.'],['03','Development & Testing','Milestone-based development, review and quality checks.'],['04','Deployment & Support','Launch, training, documentation and agreed support.']].map(([n,t,d])=><article key={n} className="glass rounded-3xl p-7"><p className="text-sm font-black text-accent">{n}</p><h3 className="mt-12 text-xl font-bold">{t}</h3><p className="mt-3 text-sm text-white/55 light:text-black/55">{d}</p></article>)}</div></Section>

  <Section id="pricing" label="STARTING PACKAGES" title="Flexible packages based on your business needs." intro="Final pricing depends on features, integrations, timeline and deployment requirements."><div className="mt-10 grid gap-5 lg:grid-cols-3"><Price name="Business Website" price="₱20,000+" items={['Responsive website','Up to 5 key pages','Basic SEO setup','Domain and hosting assistance','30 days support']}/><Price featured name="Business Platform" price="₱50,000+" items={['Custom dashboard','Roles and permissions','Business workflow','Reports and analytics','Deployment and training']}/><Price name="Enterprise System" price="₱120,000+" items={['Advanced modules','Cloud architecture','Multi-branch readiness','Custom integrations','3 months support']}/></div></Section>

  <section id="contact" className="mx-auto max-w-7xl px-5 py-24"><motion.div {...fade} className="overflow-hidden rounded-[2.5rem] border border-accent/25 bg-gradient-to-br from-accent/15 via-panel to-ink p-7 md:p-12"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><Label>START A PROJECT</Label><h2 className="section-title mt-4">Let&apos;s discuss the system your business needs.</h2><p className="mt-5 text-white/55">Share your requirements and target timeline. Your inquiry will be sent directly to support@abotrix.com.</p><a href="mailto:support@abotrix.com" className="mt-8 inline-flex items-center gap-3 text-accent"><Mail/> support@abotrix.com</a></div><form action="https://formsubmit.co/support@abotrix.com" method="POST" className="grid gap-4"><input type="hidden" name="_subject" value="New ABOTRIX Portfolio Inquiry"/><input type="hidden" name="_captcha" value="false"/><input type="hidden" name="_template" value="table"/><div className="grid gap-4 sm:grid-cols-2"><input required name="name" placeholder="Your name" className="field"/><input required type="email" name="email" placeholder="Email address" className="field"/></div><div className="grid gap-4 sm:grid-cols-2"><input name="phone" placeholder="Mobile number" className="field"/><select name="project_type" className="field"><option>Business Website</option><option>Custom Business Platform</option><option>POS System</option><option>SaaS Platform</option><option>Other</option></select></div><textarea required name="details" rows={6} placeholder="Tell me about your project..." className="field"/><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-accent px-6 py-4 font-bold text-ink">Send Inquiry <ArrowRight size={18}/></button><p className="text-xs text-white/35">The first submission may require one-time FormSubmit email activation.</p></form></div></motion.div></section>

  <footer className="border-t border-white/10 py-12 light:border-black/10"><div className="mx-auto grid max-w-7xl gap-8 px-5 md:grid-cols-[1.3fr_1fr_1fr_1fr]"><div><p className="text-xl font-extrabold">ABOTRIX</p><p className="mt-3 max-w-xs text-sm text-white/45 light:text-black/45">Practical business software, modern websites and cloud-ready platforms.</p></div><FooterCol title="Quick Links" items={['About','Projects','Pricing','Contact']}/><FooterCol title="Services" items={['Web Development','POS Systems','SaaS Platforms','Cloud Deployment']}/><div><p className="font-bold text-accent">Contact</p><p className="mt-4 text-sm text-white/55 light:text-black/55">support@abotrix.com</p><p className="mt-2 text-sm text-white/55 light:text-black/55">Cavite, Philippines</p></div></div><div className="mx-auto mt-10 flex max-w-7xl flex-col gap-3 border-t border-white/10 px-5 pt-6 text-sm text-white/35 light:border-black/10 light:text-black/35 sm:flex-row sm:justify-between"><p>© {year} Rod Maglapid · ABOTRIX</p><p>Software Developer Portfolio V4</p></div></footer>
 </main></>;
}
function Label({children}:{children:React.ReactNode}){return <span className="inline-flex rounded-full bg-accent/10 px-3 py-1 text-xs font-bold tracking-wider text-accent">{children}</span>}
function Section({id,label,title,intro,children}:{id:string,label:string,title:string,intro:string,children:React.ReactNode}){return <section id={id} className="mx-auto max-w-7xl px-5 py-24"><motion.div {...fade}><Label>{label}</Label><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="section-title max-w-4xl">{title}</h2><p className="max-w-md text-white/55 light:text-black/55">{intro}</p></div>{children}</motion.div></section>}
function Stat({n,label}:{n:string,label:string}){return <div className="glass rounded-2xl p-4"><p className="text-2xl font-black text-accent">{n}</p><p className="text-xs text-white/45 light:text-black/45">{label}</p></div>}
function Metric({icon,value,label}:{icon:React.ReactNode,value:string,label:string}){return <div className="flex items-center gap-3"><span className="text-accent">{icon}</span><div><p className="font-black">{value}</p><p className="text-xs text-white/45 light:text-black/45">{label}</p></div></div>}
function Social({icon,label}:{icon:React.ReactNode,label:string}){return <a href="#contact" aria-label={label} className="grid h-9 w-9 place-items-center rounded-full border border-white/10 transition hover:border-accent hover:text-accent light:border-black/10">{icon}</a>}
function Price({name,price,items,featured=false}:{name:string,price:string,items:string[],featured?:boolean}){return <article className={`rounded-3xl border p-7 ${featured?'border-accent bg-accent/10 shadow-glow':'glass'}`}><p className="text-sm font-bold text-accent">{name}</p><h3 className="mt-4 text-4xl font-black">{price}</h3><p className="mt-2 text-xs text-white/40 light:text-black/40">Final quotation depends on scope.</p><div className="mt-7 grid gap-3">{items.map(x=><p key={x} className="flex items-center gap-3 text-sm"><Check size={16} className="text-accent"/>{x}</p>)}</div><a href="#contact" className={`mt-8 inline-flex w-full items-center justify-center rounded-xl px-5 py-3 font-bold ${featured?'bg-accent text-ink':'border border-white/15 light:border-black/15'}`}>Request a Quote</a></article>}
function FooterCol({title,items}:{title:string,items:string[]}){return <div><p className="font-bold text-accent">{title}</p><div className="mt-4 grid gap-2 text-sm text-white/55 light:text-black/55">{items.map(x=><a key={x} href="#contact">{x}</a>)}</div></div>}
